instantiate package

In [8]:
using Pkg
Pkg.activate("../")
Pkg.instantiate()
using TeneT
using TeneT_demo

  Activating project at `e:\1 - research\4.9 - AutoDiff\TeneT_demo`


    Updating registry at `E:\juliapkg\registries\General.toml`


    Updating `E:\1 - research\4.9 - AutoDiff\TeneT_demo\Project.toml`
  [5789e2e9] + FileIO v1.16.0
  [d3d80556] + LineSearches v7.2.0
  [ebe7aa44] + OMEinsum v0.7.2
  [6f22d1fd] + OMEinsumContractionOrders v0.8.1
  [429524aa] + Optim v1.7.4
  [260a78e0] + TeneT v0.1.0
  [e88e6eb3] + Zygote v0.6.51
    Updating `E:\1 - research\4.9 - AutoDiff\TeneT_demo\Manifest.toml`
  [621f4979] + AbstractFFTs v1.2.1
  [1520ce14] + AbstractTrees v0.4.3
  [79e6a3ab] + Adapt v3.4.0
  [30b0a656] + ArrayInterfaceCore v0.1.26
  [ab4f0b2a] + BFloat16s v0.2.0
  [a9ab73d0] + BatchedRoutines v0.2.2
  [7cffe744] + BetterExp v0.1.0
  [fa961155] + CEnum v0.4.2
  [052768ef] + CUDA v3.12.0
  [082447d4] + ChainRules v1.45.0
  [d360d2e6] + ChainRulesCore v1.15.6
  [9e997f8a] + ChangesOfVariables v0.1.4
  [861a8166] + Combinatorics v1.0.2
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.5.0
  [187b0558] + ConstructionBase v1.4.1
  [9a962f9c] + DataAPI v1.13.0
  [864edb3b] + DataStructures v0.18.13


  [3587e190] + InverseFunctions v0.1.8
  [92d709cd] + IrrationalConstants v0.1.1
  [c8e1da08] + IterTools v1.4.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [033835bb] + JLD2 v0.4.29
  [692b3bcd] + JLLWrappers v1.4.1
  [682c06a0] + JSON v0.21.3
  [0b1a1467] + KrylovKit v0.5.4
  [929cbde3] + LLVM v4.14.1
  [d3d80556] + LineSearches v7.2.0
  [2ab3a3ac] + LogExpFunctions v0.3.19
  [1914dd2f] + MacroTools v0.5.10
  [e1d29d7a] + Missings v1.0.2
  [d41bc354] + NLSolversBase v7.8.3
  [77ba4419] + NaNMath v1.0.1
  [ebe7aa44] + OMEinsum v0.7.2
  [6f22d1fd] + OMEinsumContractionOrders v0.8.1
  [429524aa] + Optim v1.7.4
  [bac558e1] + OrderedCollections v1.4.1
  [d96e819e] + Parameters v0.12.3
  [69de0a69] + Parsers v2.5.1
  [85a6dd25] + PositiveFactorizations v0.2.4
  [21216c6a] + Preferences v1.3.0
  [74087812] + Random123 v1.6.0
  [e6cf234a] + RandomNumbers v1.5.3
  [c1ae055f] + RealDot v0.1.0
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
  [efcf1570] + Setfield v1.1.1


  [dad2f222] + LLVMExtra_jll v0.0.16+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [7b1f6079] + FileWatching
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl


  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [4536629a] + OpenBLAS_jll
  [05823500] + OpenLibm_jll
  [83775a58] + Zlib_jll
  [8e850b90] + libblastrampoline_jll


  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll


┌ Info: OMEinsum loaded the CUDA module successfully
└ @ OMEinsum E:\juliapkg\packages\OMEinsum\vgB8s\src\cueinsum.jl:117


# 2D classical Ising model
The ''energy'' of a configuration $\sigma$ is given by the Hamiltonian function:

$H(\sigma) = -\sum_{\langle i~j\rangle} J \sigma_i \sigma_j$  ($J>0$)

The Boltzmann factor is:

$W_{i~j} = e^{-\beta E_{i~j}}$

We can solve this model by TeneT.jl in follow steps:

## Step 1: define M tensor
 <img src="../picture/build_M_tensor.png" width = "30%" height = "30%" align=center />

In [3]:
using Test

@testset "Ising model_tensor" for Ni in [1,2], Nj in [1,2]
    model = Ising(Ni,Nj,0.5)
    @test size(model_tensor(model, Val(:bulk)))   == (2,2,2,2,Ni,Nj)
    @test size(model_tensor(model, Val(:mag) ))   == (2,2,2,2,Ni,Nj)
    @test size(model_tensor(model, Val(:energy))) == (2,2,2,2,Ni,Nj)
end

Test Summary:      | Pass  Total
Ising model_tensor |    3      3
Test Summary:      | Pass  Total
Ising model_tensor |    3      3
Test Summary:      | Pass  Total
Ising model_tensor |    3      3
Test Summary:      | Pass  Total
Ising model_tensor |    3      3


4-element Vector{Any}:
 Test.DefaultTestSet("Ising model_tensor", Any[], 3, false, false)
 Test.DefaultTestSet("Ising model_tensor", Any[], 3, false, false)
 Test.DefaultTestSet("Ising model_tensor", Any[], 3, false, false)
 Test.DefaultTestSet("Ising model_tensor", Any[], 3, false, false)

## Step 2: use TeneT.obs_env to get environment

In [4]:
using Random
Random.seed!(100)

β = 0.5
model = Ising(1, 1, β)
M = model_tensor(model, Val(:bulk))
env = TeneT.obs_env(M; χ=10, maxiter=10, miniter=1, 
                    updown=false, verbose=true, show_every=1);

↑ random initial 1×1 vumps_χ10 environment-> 

vumps@step: 1, error=Inf


vumps@step: 2, error=0.01730159744333545
vumps@step: 3, error=0.0006110217932778949
vumps@step: 4, error=8.525419213658111e-7
vumps@step: 5, error=1.486693561895049e-7
vumps@step: 6, error=3.5210780596961775e-8
vumps@step: 7, error=7.535505333349743e-9
vumps@step: 8, error=1.640536608963289e-9


vumps@step: 9, error=3.7020363904278236e-10
vumps done@step: 9, error=8.508814802635002e-11


## Step 3: use env to calculate observable

In [6]:
using TeneT_demo: magofβ

@testset "$(Ni)x$(Nj) ising forward with $atype" for Ni = [1], Nj = [1], atype = [Array]
    Random.seed!(100)
    β = 0.5
    model = Ising(Ni, Nj, β)
    M = atype(model_tensor(model, Val(:bulk)))
    env = obs_env(M; χ = 10, maxiter = 10, miniter = 1, 
         infolder = "./example/data/$model/", 
        outfolder = "./example/data/$model/", 
        updown = false, verbose = false, savefile = false
        )
    @test observable(env, model, Val(:Z)     ) ≈ 2.789305993957602
    @test observable(env, model, Val(:mag)   ) ≈ magofβ(model) 
    @test observable(env, model, Val(:energy)) ≈ -1.745564581767667
end

Test Summary:                | Pass  Total
1x1 ising forward with Array |    3      3


1-element Vector{Any}:
 Test.DefaultTestSet("1x1 ising forward with Array", Any[], 3, false, false)

## Step 4(optional): calculate energy by Zygote.gradient

In [8]:
using Zygote

@testset "$(Ni)x$(Nj) ising backward with $atype" for Ni = [1], Nj = [1], atype = [Array]
    Random.seed!(100)
    function logZ(β)
        model = Ising(1, 1, β)
        M = model_tensor(model, Val(:bulk))
        env = obs_env(M;χ = 10, maxiter = 10, miniter = 1, 
                        updown = false, verbose = false, savefile = false
                    )
        log(real(observable(env, model, Val(:Z))))
    end
    @test Zygote.gradient(β->-logZ(β), 0.5)[1] ≈ -1.745564581767667
end

Test Summary:                 | Pass  Total
1x1 ising backward with Array |    1      1


1-element Vector{Any}:
 Test.DefaultTestSet("1x1 ising backward with Array", Any[], 1, false, false)

<font size=5>*try different Temperature $\beta$, bond dimension $\chi$, unit cell size $Ni \times Nj$ and CuArray with GPU!*</font>

# Finding the Ground State of infinite 2D Heisenberg model
The Heisenberg Hamiltonian function is:

$H = \sum_{\langle i~j\rangle} J^x S_i^x S_j^x + J^y S_i^y S_j^y + J^z S_i^z S_j^z $




In [14]:
@testset "hamiltonian" begin
    h = hamiltonian(Heisenberg(1,1))
    @test size(h) == (2,2,2,2)
    rh = reshape(permutedims(h,(1,3,2,4)),4,4)
    @test rh' == rh
end

Test Summary: | Pass  Total
hamiltonian   |    2      2


Test.DefaultTestSet("hamiltonian", Any[], 2, false, false)

The algorithm variationally minimizes the energy of a Heisenberg model on a two-dimensional infinite lattice using a form of gradient descent.

## Step 1: initial iPEPS tensor

In [6]:
@testset "init_ipeps" for Ni = [1,2], Nj = [1,2], D in [2,3], χ in [10]
    model = Heisenberg(Ni,Nj)
    A, key = init_ipeps(model; Ni=Ni, Nj=Nj, D=D, χ=χ);
    @test size(A) == (D,D,D,D,2,Ni,Nj)
end

random initial BCiPEPS ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\D2_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial BCiPEPS ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\D3_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial BCiPEPS ./data/1x2/Heisenberg{Float64}(1, 2, 1.0, 1.0, 1.0)\D2_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial BCiPEPS ./data/1x2/Heisenberg{Float64}(1, 2, 1.0, 1.0, 1.0)\D3_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial BCiPEPS ./data/2x1/Heisenberg{Float64}(2, 1, 1.0, 1.0, 1.0)\D2_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial BCiPEPS ./data/2x1/Heisenberg{Float64}(2, 1, 1.0, 1.0, 1.0)\D3_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1
random initial B

   1      1
random initial BCiPEPS ./data/2x2/Heisenberg{Float64}(2, 2, 1.0, 1.0, 1.0)\D3_χ10_tol1.0e-10_maxiter10.jld2
Test Summary: | Pass  Total
init_ipeps    |    1      1


8-element Vector{Any}:
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)
 Test.DefaultTestSet("init_ipeps", Any[], 1, false, false)

## Step 2: contract the tensor network to get the energy

We don't have constraints on ipeps, so the horizontal and vertical bond energy is different and we should use both the up and down environment.

In [11]:
using TeneT_demo: optcont, energy

@testset "energy" for Ni = [1], Nj = [1], D in [2,3], χ in [10]
    model = Heisenberg(Ni,Nj)
    A, key = init_ipeps(model; Ni=Ni, Nj=Nj, D=D, χ=χ)
    oc = optcont(D, χ)
    h = hamiltonian(model)
    @show energy(h, A, oc, key; verbose = true, savefile = true)
end

random initial BCiPEPS ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\D2_χ10_tol1.0e-10_maxiter10.jld2
Horizontal Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
Vertical Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
↑ 

vumps 1×1 environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\up_D4_χ10.jld2 -> vumps done@step: 1, error=9.680166995539702e-12
←→ observable environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\obs_D4_χ10.jld2


↓ vumps 1×1 environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\down_D4_χ10.jld2 -> vumps done@step: 1, error=1.4380085393498025e-11
===========1,1===========
Horizontal energy = 0.24991787873537294 - 8.698045466742041e-15im
Vertical energy = 0.2499441377150105 + 1.4200702929427347e-12im
e = 0.4998620164503834 + 1.4113722474759926e-12im
energy(h, A, oc, key; verbose = true, savefile = true) = 0.4998620164503834 + 1.4113722474759926e-12im
Test Summary: |
energy        | No tests
random initial BCiPEPS ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\D3_χ10_tol1.0e-10_maxiter10.jld2
Horizontal Contraction Complexity(seed=60)(22.5340254495046, 14.983706192659348)
Vertical Contraction Complexity(seed=60)

(22.5340254495046, 14.983706192659348)
↑ 

vumps 1×1 environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\up_D9_χ10.jld2 -> vumps done@step: 10, error=6.204419914720449e-7
←→ observable environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\obs_D9_χ10.jld2
↓ vumps 1×1 environment load from ./data/1x1/Heisenberg{Float64}(1, 1, 1.0, 1.0, 1.0)\down_D9_χ10.jld2 -> 

vumps done@step: 10, error=6.706873852398704e-9
===========1,1===========
Horizontal energy = 0.24996753113950954 + 8.258793346112662e-13im
Vertical energy = 0.24994307688102824 - 1.4255559620188749e-9im
e = 0.49991060802053777 - 1.4247300826842636e-9im
energy(h, A, oc, key; verbose = true, savefile = true) = 0.49991060802053777 - 1.4247300826842636e-9im
Test Summary: |
energy        | No tests


2-element Vector{Any}:
 Test.DefaultTestSet("energy", Any[], 0, false, false)
 Test.DefaultTestSet("energy", Any[], 0, false, false)

## Step 3: optimise the ipeps by gradient

The ground state of Heisenberg model is antiferromagnetic, which means we should use $2 \times 2$ unit cell to simulate it directly.

 <img src="../picture/antiferromagnetic_configuration.png" width = "30%" height = "30%" align=center />

In [13]:
using Optim

@testset "optimise_ipeps" for Ni = [2], Nj = [2], D in [2], χ in [10]
    model = Heisenberg(Ni,Nj,1.0,1.0,1.0)
    A, key = init_ipeps(model; Ni=Ni, Nj=Nj, D=D, χ=χ, verbose= false)
    optimise_ipeps(A, key; f_tol = 1e-6, opiter = 10, optimmethod = LBFGS(m = 20))
end

Horizontal Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
Vertical Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
time  steps   energy           grad_norm


0.0   0       0.4497262425    0.1304296944


4.0   1       -0.456339363    0.1447771017


7.7   2       -0.4957160602    0.1154829916


10.3   3       -0.5288425844    0.0542520603


29.4   4       -0.5782739041    0.1313472721


37.1   5       -0.5921715912    0.1236647747


47.4   6       -0.6190859349    0.0871452675


51.4   7       -0.638826843    0.0373215939


61.8   8       -0.6472531059    0.0287116345


76.4   9       -0.6531850204    0.0195096561


82.4   10       -0.6557469587    0.0103425538


Test Summary:  |
optimise_ipeps | No tests


1-element Vector{Any}:
 Test.DefaultTestSet("optimise_ipeps", Any[], 0, false, false)

<font size=5>*The configuration is ABBA, so we can simplify the ipeps by only using A and B two tensors. Try to verify it!*</font>

<font size=5>*If we only want ground state, the follow $1 \times 1$ unit cell is also correct. Think about why.*</font>

 Hint: Flip the second spin.

In [14]:
@testset "optimise_ipeps" for Ni = [1], Nj = [1], D in [2], χ in [10]
    model = Heisenberg(Ni,Nj,-1.0,-1.0,1.0)
    A, key = init_ipeps(model; Ni=Ni, Nj=Nj, D=D, χ=χ, verbose= false)
    optimise_ipeps(A, key; f_tol = 1e-6, opiter = 10, optimmethod = LBFGS(m = 20))
end

Horizontal Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
Vertical Contraction Complexity(seed=60)(18.501837184902293, 12.643856189774723)
time  steps   energy           grad_norm


0.0   0       -0.4263991379    0.2737298683


2.3   1       -0.4600862164    0.2475836881


4.0   2       -0.5097300104    0.0703197008


6.7   3       -0.5310755475    0.2559850562


12.3   4       -0.5642197651    0.1839739683


15.9   5       -0.5945417453    0.2186637439


18.6   6       -0.6101134968    0.1065048687


24.5   7       -0.6495478096    0.0508729128


26.7   8       -0.6557402791    0.0467743582


29.1   9       -0.6583718195    0.0184073917


30.8   10       -0.659048637    0.011347839


Test Summary:  |
optimise_ipeps | No tests


1-element Vector{Any}:
 Test.DefaultTestSet("optimise_ipeps", Any[], 0, false, false)